[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "setupEM"
dynamic = ["version"]
description = "Python tool for configuration of gds2palace workflow with GUI."
license = "GPL-3.0-or-later"
readme = "README_pypi.md"
authors = [
    { name = "Volker Muehlhaus", email = "volker@muehlhaus.com" }
]
dependencies = [
    "gds2palace>=0.4.3",
    "PySide6",
    "shiboken6",
    "scipy",
    "requests",
    "scikit-rf",
    "matplotlib",
    "numpy",
    "gdspy",
    "meshio"
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/VolkerMuehlhaus/setupEM"
Repository = "https://github.com/VolkerMuehlhaus/setupEM"
Changelog = "https://github.com/VolkerMuehlhaus/setupEM/blob/main/doc/CHANGES.md"

[project.scripts]
setupEM = "setupEM.setupEM:main"
setupThermal = "setupEM.setupThermal:main"
stackupEditor = "setupEM.stackupEditor:main"
resultViewer = "setupEM.result_viewer:main"

[tool.setuptools.dynamic]
version = {attr = "setupEM.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["setupEM*"]

[tool.setuptools.package-data]
"setupEM" = ["data/*.xml"]

